CREATE TABLE IF NOT EXISTS Products
(
    ID           BIGSERIAL    NOT NULL,
    NAME         VARCHAR(256) NOT NULL,
    DESCRIPTION  VARCHAR(4096),
    PRICE        NUMERIC(10, 2) DEFAULT 0 CHECK (PRICE >= 0),
    AVAILABILITY BOOLEAN        DEFAULT false
);